Add code sniffer in travis.yml : 3
nirgn975/open-pension-crawler pull request #5
Opened 2016-09-28 19:31 UTC by daniellevi1

2016-09-28 20:21 UTC, nirgn975 commented
@daniellevi1 
- Assign this PR to yourself.
- Add `WIP: ..` in the title.
- Remove the `: 3` from the title.

2016-09-28 20:26 UTC, nirgn975 requested changes

2016-09-28 20:26 UTC, nirgn975 commented on .travis.yml
> +python:
Because we only have one version do it like this: `python: 3.5`

2016-09-28 20:26 UTC, nirgn975 commented on .travis.yml
> +
There is no need for this white space, please remove one of the `enter`s.

2016-09-28 20:26 UTC, nirgn975 commented on .travis.yml
> +
There is no need for this white space, please remove one of the `enter`s.

2016-09-28 20:26 UTC, nirgn975 commented on .travis.yml
> +  - if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then
This is a script, and you don't need the `if` so you actually want something like this:
```yml
install:
  # Install code sniffer.
  - pip install pycodestyle
  - pip install --upgrade pycodestyle
  - source ~/.bash_profile
  - source ~/.bashrc
```

2016-09-28 20:26 UTC, nirgn975 commented on .travis.yml
> +script:
Same as before, every command in a different line, like:
```yml
script:
  - pycodestyle --show-source --max-line-length=119 --show-pep8 .
```

And remove `- if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then` and `fi`

2016-09-28 23:56 UTC, isranumbers commented
for some inspiration:
https://www.youtube.com/watch?v=S0gMOjjH2fw

2016-09-29 00:21 UTC, daniellevi1 commented
@nirgn975 I tried to pull 2 commits to this PR and it failed because it can't build, why?
Another thing, how to delete commit in PR?
Also, 'Add a link to the issue (by add an hashtag and the issue number) in the PR description.' - it's not working to me.

2016-09-29 04:47 UTC, nirgn975 requested changes

2016-09-29 04:47 UTC, nirgn975 commented on .travis.yml
> +
There is 2 `enters` at the EOF (End Of File), There is no need for such a whitespace, one is enough.

2016-09-29 04:47 UTC, nirgn975 commented on .travis.yml
> +    pip install pycodestyle;
For every new line inside `install:` / `script:` / etc you will need `-` like:
```yml
- pip install pycodestyle
- pip install --upgrade pycodestyle
- source ~/.bash_profile
- source ~/.bashrc
```

2016-09-29 04:47 UTC, nirgn975 commented on .travis.yml
> +    pip install pycodestyle;
And notice I remove the semicolons `;`.

2016-09-29 04:47 UTC, nirgn975 commented on .gitignore
> +
There is 2 enters at the EOF (End Of File), There is no need for such a whitespace, one is enough.

2016-09-29 04:47 UTC, nirgn975 commented on .gitignore
> +
There is no need for such a whitespace, delete this whitespace (`enter`).

2016-09-29 05:00 UTC, nirgn975 commented
@daniellevi1 
- What do you mean by _"tried to pull 2 commits to this PR"_ ?
- There is a way to delete a commit, but it's not "best practice", so don't do this, just do your changes and do another commit. As a rule of thumb never try to get back to the past and change it (;

  We all made mistakes all the time, and open source means we don't have to shy about this. Our work is the way and not the end result (we don't just released the end result in the "perfect" form). Others looking at our work, help us, and correct us is a good thing, this is what great about open source.

- Revert the title to `WIP: Add code sniffer in travis.yml`. The title shouldn't contain the issue number.
- Edit your PR description by click on the pan:
![wip__3_by_daniellevi1_ _pull_request__5_ _nirgn975_open_pension_scraper](https://cloud.githubusercontent.com/assets/3472902/18941535/b21a99f2-861a-11e6-8d55-a8ed5bdb1c48.png)

  And try to add a link to the issue like this:
![wip__3_by_daniellevi1_ _pull_request__5_ _nirgn975_open_pension_scraper](https://cloud.githubusercontent.com/assets/3472902/18941513/935f47a6-861a-11e6-9ded-7361ef14e506.png)

  And just press `enter`.

2016-09-29 05:12 UTC, nirgn975 requested changes

2016-09-29 05:12 UTC, nirgn975 commented on .travis.yml
> +    pip install pycodestyle;
And keep only 2 spaces and then the `-`, then another space and the the command.
Example:
```yml
  - somethin
```

2016-09-29 05:12 UTC, nirgn975 commented on .travis.yml
> +    pycodestyle --show-source --max-line-length=119 --show-pep8 .
Keep only 2 spaces, then `-`, another space and then the command, like:
```yml
script:
  # Run code sniffer on the scraper directory.
  - pycodestyle --show-source --max-line-length=119 --show-pep8 .
```

2016-09-29 05:14 UTC, nirgn975 commented
@daniellevi1 Don't forget about edit the `README.md` file.

2016-09-29 09:00 UTC, daniellevi1 commented on .travis.yml
> +    pycodestyle --show-source --max-line-length=119 --show-pep8 .
@nirgn975 
 -  "tried to pull 2 commits to this PR" I was confiused, I ment 'tried to push 2 commits to this PR' and that failed.
 -  I wanted to delete commit to make the PR more orderly

2016-09-29 10:07 UTC, daniellevi1 commented
@nirgn975
  - I pushed the fix commit, but I don't see it. And all  the PR is failed. Do i need to open new PR?
  - "tried to pull 2 commits to this PR" I was confiused, I ment 'tried to push 2 commits to this PR' and that failed.
  - I wanted to delete commit to make the PR more orderly

2016-09-29 11:28 UTC, nirgn975 commented
The PR starting to look **great!** :+1:
Don't worry about the order of the PR itself.

Now, I have a feeling travis should work, let's check why it fail. We can go to the last `commit` and put the mouse on the red `x`:
![wip__add_code_sniffer_in_travis_yml__add_gitignore__edit_readme_by_daniellevi1_ _pull_request__5_ _nirgn975_open_pension_scraper](https://cloud.githubusercontent.com/assets/3472902/18950472/ab17a39c-8648-11e6-8fd7-5c8587f6ee45.png)

If you click it you'll be redirect to `Travis-CI`. There you'll see the script in `.travis.yml` run. First of all it look like travis managed to install everything, so that's good. And you can see the last `install` command was the command that run the `sniffer`. After it you can see that he tells us there is an error in file `./scraper/scraper/settings.py` in line 19, and the start (character 1). The error number is `E2665` and the error said `block comment should start with '# '`. Then he print the line where our code is not correct. And he try to tell us how to fix it (in this case `Separate inline comments by at least two spaces.`).

Usually you'll need to go over the output on travis, fix the errors, `commit`, and let travis run again. But in this case, those lines are options, and we don't want to make them look like regular comments, and we also want to save them there. And it's a settings file.. So let's just exclude this file, so the sniffer will not check it (`--exclude=scraper/scraper/settings.py`).

2016-09-29 11:34 UTC, nirgn975 requested changes

2016-09-29 11:34 UTC, nirgn975 commented on README.md
> +Open Pension Scraper
This should be in `h1`, like: `# Open Pension Scraper`

2016-09-29 11:34 UTC, nirgn975 commented on README.md
> +
There is no need for this whitespace.

2016-09-29 11:34 UTC, nirgn975 commented on README.md
> +Pre Requirements
This should be an `h2`, like: `## Pre Requirements`.

2016-09-29 11:34 UTC, nirgn975 commented on README.md
> +    Make sure you have Python 3.x and pip installed.
Let's make it a bullet list, so it should be like:
```markdown
  * Make sure you have Python 3.x and pip installed.
  * NodeJS.
```

2016-09-29 11:34 UTC, nirgn975 commented on README.md
> +Installation
This should be an `h2`, like: `## Installation`.

2016-09-29 11:34 UTC, nirgn975 commented on README.md
> +    Not yet.
There is no need for indentation here

2016-09-29 11:34 UTC, nirgn975 commented on README.md
> +Tests
This should be an `h2`, like: `## Tests `.

2016-09-29 11:34 UTC, nirgn975 commented on README.md
> +Contribute
This should be an `h2`, like: `## Contribute `.

2016-09-29 11:34 UTC, nirgn975 commented on README.md
> +    Not yet.
There is no need for indentation here

2016-09-29 11:39 UTC, nirgn975 requested changes

2016-09-29 11:39 UTC, nirgn975 commented on README.md
> +    NodeJS.
We don't need `NodeJS` to install this project, so remove it.

2016-09-29 16:13 UTC, nirgn975 commented
@daniellevi1 looks good! If you finish just assign the PR to me (and remove yourself), write something like "ready", and remove the `WIP:` from the title.

2016-09-29 16:17 UTC, nirgn975 commented
@daniellevi1 Strange.. the sniffer still check the `settings.py` file. lets try to put `./` at the start (`--exclude=./scraper/scraper/setting.py`).

Overall the PR looks good! If Travis-CI work with our little trick, that's mean you finish, just assign the PR to me (and remove yourself), write something like "ready", and remove the WIP: from the title.

2016-09-29 17:27 UTC, nirgn975 commented
@daniellevi1 I see it still not working. Can you find why? go over the log in Travis-CI try to figure out why this command not works. Keep in mind that in `open_pension` repo it works.
Read the path we `exclude` and the path to the file the sniffer check.

2016-09-29 18:27 UTC, nirgn975 approved these changes

2016-09-29 18:30 UTC, merged

2016-09-29 18:31 UTC, daniellevi1 commented
OMG