Add Travis=CI badge
nirgn975/open-pension-crawler pull request #9
Opened 2016-09-30 20:58 UTC by daniellevi1

2016-10-01 07:31 UTC, nirgn975 requested changes

2016-10-01 07:31 UTC, nirgn975 commented on README.md
> +[![Build Status][travis-image]][travis-url] [![Join the chat at https://gitter.im/open-pension/Lobby][gitter-image]][gitter-url]
You added both `travis` and `gitter`, keep only `travis`.

And this is just the urls for the image and the links. look at the [README](https://raw.githubusercontent.com/hasadna/open_pension/master/README.md) at the end of the file for the relevant links (they should be a little different, there are the links to open pension travis, we need our travis).

2016-10-01 07:32 UTC, nirgn975 commented
By the way, you can go to the `code` section on this repo and move branch, to check how it will look:
![selection_003](https://cloud.githubusercontent.com/assets/3472902/19012571/6adc4046-87c2-11e6-9531-98e424ada0af.png)

2016-10-01 11:52 UTC, daniellevi1 commented
@nirgn975  Thanks for the comments, Markdown language is used in other places than readme.me in github?

2016-10-01 13:36 UTC, nirgn975 requested changes

2016-10-01 13:36 UTC, nirgn975 commented on README.md
> +
You have 2 whitespaces at the the of the file, remove one.

2016-10-01 13:39 UTC, nirgn975 commented
@daniellevi1 
Yes, in gaining popularity especially in website who're appeal to developers, geeks, etc (see [Markdown](https://en.wikipedia.org/wiki/Markdown)).

2016-10-01 22:36 UTC, daniellevi1 commented
@nirgn975 Usually I leave 2 white spaces between 'paragraphs', it is common syntax to leave 1 in .md?

2016-10-05 07:42 UTC, nirgn975 commented
@daniellevi1 Yes, but not just in `md` files, in every file. Leave one space in the end of each and every file.

2016-10-05 07:42 UTC, nirgn975 approved these changes

2016-10-05 07:43 UTC, merged